<a href="https://colab.research.google.com/github/iam-krj/Deep-Learning/blob/main/1_DL_Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PERCEPTRON

#Importing Libraries

In [ ]:
from numpy import array
from numpy import random
from numpy import dot
from random import choice

#Activation Function

In [ ]:
activationFn = lambda x: 0 if x<0 else 1

#Initialise Dataset

In [ ]:
dataset = [
           (array([0,0,1]), 0), #array ([x,y,b],e) x,y = input, b= bias, e = expected output to validate
           (array([0,1,1]), 1),
           (array([1,0,1]), 1),
           (array([1,1,1]), 1),
]
print(dataset)
print(array([0,0,1]), 0)

[(array([0, 0, 1]), 0), (array([0, 1, 1]), 1), (array([1, 0, 1]), 1), (array([1, 1, 1]), 1)]
[0 0 1] 0


#Initializing Random numbers for Weights

In [ ]:
weights = random.rand(3)
weights

array([0.92936036, 0.48250855, 0.08808527])

Initializing additional values

In [ ]:
r = 0.2 #learning rate
n = 100 #Number of Iteration

#Training our Model

In [ ]:
for j in range (n):
    x, expected = choice(dataset)
    result = dot(weights, x)
    err = expected-activationFn(result)
    weights +=r*err *x
    

##Evaluating Model

In [ ]:
for x, _ in dataset:
    result = dot(x, weights)
    print("Input: {} ResultBAFn: {} ResultAFn: {}".format(x[:2],round(result,3),activationFn(result)))

Input: [0 0] ResultBAFn: -0.112 ResultAFn: 0
Input: [0 1] ResultBAFn: 0.371 ResultAFn: 1
Input: [1 0] ResultBAFn: 0.817 ResultAFn: 1
Input: [1 1] ResultBAFn: 1.3 ResultAFn: 1


#Deep Learning Terminology Day1

