<a href="https://colab.research.google.com/github/iam-krj/Deep-Learning/blob/main/2_DL_ActivationFunction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Importing Libraries

In [4]:
from numpy import array
from numpy import random
from numpy import dot
from random import choice

#Activation Function

In [5]:
activationFn = lambda x: 0 if x<0 else 1

#Initialise dataset

In [9]:
dataset = [
           (array([0,0,1]), 0), #array ([x,y,b],e) x,y = input, b= bias, e = expected output to validate
           (array([0,1,1]), 1),
           (array([1,0,1]), 1),
           (array([1,1,1]), 1),
]
print(dataset)
weights = random.rand(3)

[(array([0, 0, 1]), 0), (array([0, 1, 1]), 1), (array([1, 0, 1]), 1), (array([1, 1, 1]), 1)]


##Initializing additional variables

In [7]:
r = 0.2#learning rate
n= 100 #number of iterations

#Activation Function

##Training and Evaluating using STEP Activation Function

In [10]:
activationFn = lambda x :0 if x< 0 else 1 #step activation function(if i/p is negative o/p is 0)
for j in range(n):
    x, expected = choice(dataset)
    result = dot(weights, x)
    err= expected - activationFn(result)
    weights += r * err * x

for x, _ in dataset:
    result = dot(x, weights)
    print("ResultBAFn: {} ResultAFn : {}".format(round(result,3), activationFn(result)))

ResultBAFn: -0.067 ResultAFn : 0
ResultBAFn: 0.866 ResultAFn : 1
ResultBAFn: 0.141 ResultAFn : 1
ResultBAFn: 1.074 ResultAFn : 1


##Training and Evaluating using LINEAR Activation Function

In [11]:
activationFn = lambda x : x

for j in range(n):
    x, expected = choice(dataset)
    result = dot(weights, x)
    err= expected - activationFn(result)
    weights += r * err * x

for x, _ in dataset:
    result = dot(x, weights)
    print("ResultBAFn: {} ResultAFn : {}".format(round(result,3), activationFn(result)))

ResultBAFn: 0.394 ResultAFn : 0.39371142835334055
ResultBAFn: 0.997 ResultAFn : 0.9971844343677139
ResultBAFn: 0.885 ResultAFn : 0.885119320590573
ResultBAFn: 1.489 ResultAFn : 1.4885923266049461


##Training and Evaluating using SIGMOID Activation Function

In [12]:
import numpy as np
activationFn = lambda x: 1/(1+np.exp(-x))
err =[]
for j in range(n):
    x, expected = choice(dataset)
    result = dot(weights, x)
    err= expected - activationFn(result)
    weights += r * err * x

for x, _ in dataset:
    result = dot(x, weights)
    print("ResultBAFn: {} ResultAFn : {}".format(round(result,3), activationFn(result)))

ResultBAFn: -0.601 ResultAFn : 0.3540204627592593
ResultBAFn: 1.0 ResultAFn : 0.7309644301840597
ResultBAFn: 1.412 ResultAFn : 0.8041142291773022
ResultBAFn: 3.013 ResultAFn : 0.953164407086267


##Training And Evaluating using RELU Activation Function

In [13]:
activationFn = lambda x: 0 if x<0 else x
err =[]
for j in range(n):
    x, expected = choice(dataset)
    result = dot(weights, x)
    err= expected - activationFn(result)
    weights += r * err * x

for x, _ in dataset:
    result = dot(x, weights)
    print("ResultBAFn: {} ResultAFn : {}".format(round(result,3), activationFn(result)))

ResultBAFn: 0.017 ResultAFn : 0.01749560798033406
ResultBAFn: 0.607 ResultAFn : 0.606796597974284
ResultBAFn: 0.83 ResultAFn : 0.8296529547564369
ResultBAFn: 1.419 ResultAFn : 1.4189539447503867


#Training And Evaluating using SOFTMAX Activation Function

In [14]:
activationFn = lambda x: np.exp(x) / np.sum(np.exp(x), axis = 0)
err =[]
for j in range(n):
    x, expected = choice(dataset)
    result = dot(weights, x)
    err= expected - activationFn(result)
    weights += r * err * x

for x, _ in dataset:
    result = dot(x, weights)
    print("ResultBAFn: {} ResultAFn : {}".format(round(result,3), activationFn(result)))

ResultBAFn: -4.383 ResultAFn : 1.0
ResultBAFn: -3.793 ResultAFn : 1.0
ResultBAFn: -3.57 ResultAFn : 1.0
ResultBAFn: -2.981 ResultAFn : 1.0
